springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/f1db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:f1}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:f1}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true